version: '3'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keploy
      MYSQL_USER: keploy
      MYSQL_PASSWORD: keploy
    ports:
      - 3306:3306
    networks:
      - keploy
    volumes:
      - ./db:/docker-entrypoint-initdb.d

networks:
  keploy:
    name: keploy
